INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (1, 'IAM', 'IAM_USER_CREATE');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (2, 'IAM', 'IAM_USER_READ');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (3, 'IAM', 'IAM_USER_UPDATE');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (4, 'IAM', 'IAM_USER_DELETE');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (5, 'IAM', 'IAM_AUTHORITY_READ');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (6, 'IAM', 'IAM_AUTHORITY_ASSIGN');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (7, 'IAM', 'IAM_AUTHORITY_REVOKE');