INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'USER_CREATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'USER_READ');
INSERT INTO AUTHORITY(ID, NAME) VALUES (3, 'USER_UPDATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (4, 'USER_DELETE');

INSERT INTO AUTHORITY(ID, NAME) VALUES (5, 'AUTHORITY_ASSIGN');
INSERT INTO AUTHORITY(ID, NAME) VALUES (6, 'AUTHORITY_REVOKE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (7, 'TEMP_1');
INSERT INTO AUTHORITY(ID, NAME) VALUES (8, 'TEMP_2');

INSERT INTO AUTHORITY(ID, NAME) VALUES (9, 'TEMP_3');