INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (1, 'IAM', 'USER_CREATE');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (2, 'IAM', 'USER_READ');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (3, 'IAM', 'USER_UPDATE');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (4, 'IAM', 'USER_DELETE');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (5, 'IAM', 'AUTHORITY_READ');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (6, 'IAM', 'AUTHORITY_ASSIGN');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (7, 'IAM', 'AUTHORITY_REVOKE');

INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (8, 'TEMP', 'TEMP_2');
INSERT INTO AUTHORITY(ID, MODULE, NAME) VALUES (9, 'TEMP', 'TEMP_3');